# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 18:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_actor', models.CharField(max_length=50, verbose_name='Nombre Actor')),
                ('biografia', models.CharField(max_length=200, verbose_name='Biografia')),
                ('peliculas', models.CharField(max_length=200, verbose_name='Peliculas')),
            ],
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_clasificacion', models.CharField(max_length=3, verbose_name='Tipo Clasificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_genero', models.CharField(max_length=50, verbose_name='Tipo Genero')),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=75, verbose_name='Titulo')),
                ('sinopsis', models.CharField(max_length=200, verbose_name='Sinopsis')),
                ('duracion', models.CharField(max_length=15, verbose_name='Duracion')),
                ('estreno', models.BooleanField(verbose_name='Estreno')),
                ('actores', models.CharField(max_length=200, verbose_name='Actores')),
                ('clasificacion', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sistema_renta_pelicula.Clasificacion')),
                ('genero', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sistema_renta_pelicula.Genero')),
            ],
        ),
        migrations.CreateModel(
            name='RentaPelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_renta', models.DateTimeField(verbose_name='Fecha Renta')),
                ('hora_renta', models.TimeField(verbose_name='Hora Renta')),
                ('fecha_entrega', models.DateTimeField(verbose_name='Fecha Entrega')),
                ('pelicula', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sistema_renta_pelicula.Pelicula')),
                ('usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
