# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_renta_pelicula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeliculaTrayectoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pelicula_tra', models.CharField(max_length=3, verbose_name='Peliculas Trayectoria')),
            ],
        ),
        migrations.AlterField(
            model_name='actores',
            name='peliculas',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='sistema_renta_pelicula.PeliculaTrayectoria'),
        ),
    ]
