# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_renta_pelicula', '0002_auto_20161207_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actores',
            name='biografia',
        ),
        migrations.RemoveField(
            model_name='actores',
            name='peliculas',
        ),
        migrations.AddField(
            model_name='actores',
            name='trayectoria',
            field=models.CharField(default='Sin trayectoria', max_length=1000, verbose_name='Trayectoria'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PeliculaTrayectoria',
        ),
    ]
